version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps: 
      - checkout

  publish_docker_linuxamd64:
    machine:
      docker_layer_caching: true
    steps:
      - checkout  
      - run:
          command: |
            LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            LATEST_TAG=${LATEST_TAG:1} #trim v from tag
            #
            sudo docker build --pull -t rockstardev/btcpayserver:$LATEST_TAG-amd64 -t rockstardev/btcpayserver:latest-amd64 -f Dockerfile.linuxamd64 .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push rockstardev/btcpayserver:$LATEST_TAG-amd64
            sudo docker push rockstardev/btcpayserver:latest-amd64

  publish_docker_linuxarm:
    machine:
      docker_layer_caching: true
    steps:
      - checkout  
      - run:
          command: |
            sudo apt update
            sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
            LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            LATEST_TAG=${LATEST_TAG:1} #trim v from tag
            #
            sudo docker build --pull -t rockstardev/btcpayserver:$LATEST_TAG-arm32v7 -t rockstardev/btcpayserver:latest-arm32v7 -f Dockerfile.linuxarm32v7 .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push rockstardev/btcpayserver:$LATEST_TAG-arm32v7
            sudo docker push rockstardev/btcpayserver:latest-arm32v7

  publish_docker_multiarch:
    machine:
      enabled: true
      # Use Ubuntu 14.04 with bleeding edge Docker daemon 17.06.0-ce.
      image: circleci/classic:201808-01
    steps:
      - run:
          command: |
            sudo docker version
            # Turn on Experimental features
            sudo mkdir $HOME/.docker
            sudo sh -c 'echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json'
            #            
            sudo docker version
            #
            # Login and push Docker image to registry.
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker manifest create --amend rockstardev/btcpayserver:latest rockstardev/btcpayserver:latest-amd64 rockstardev/btcpayserver:latest-arm32v7
            sudo docker manifest annotate rockstardev/btcpayserver:latest rockstardev/btcpayserver:latest-amd64 --os linux --arch amd64
            sudo docker manifest annotate rockstardev/btcpayserver:latest rockstardev/btcpayserver:latest-arm32v7 --os linux --arch arm
            sudo docker manifest push rockstardev/btcpayserver:latest -p
            #new comment

workflows:
  version: 2
  build_and_test:
    jobs:
      - publish_docker_linuxamd64
      - publish_docker_linuxarm
      - publish_docker_multiarch:
          requires:
            - publish_docker_linuxamd64
            - publish_docker_linuxarm
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v[1-9]+(\.[0-9]+)*/
