version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps: 
      - checkout

  publish_docker_linuxamd64:
    machine:
      docker_layer_caching: true
    steps:
      - checkout  
      - run:
          command: |
            LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            LATEST_TAG=${LATEST_TAG:1} #trim v from tag
            #
            sudo docker build --pull -t rockstardev/btcpayserver:$LATEST_TAG-amd64 -t rockstardev/btcpayserver:latest-amd64 -f Dockerfile.linuxamd64 .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push rockstardev/btcpayserver:$LATEST_TAG-amd64
            sudo docker push rockstardev/btcpayserver:latest-amd64

  publish_docker_linuxarm:
    machine:
      docker_layer_caching: true
    steps:
      - checkout  
      - run:
          command: |
            sudo apt update
            sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
            LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            LATEST_TAG=${LATEST_TAG:1} #trim v from tag
            #
            sudo docker build --pull -t rockstardev/btcpayserver:$LATEST_TAG-arm -t rockstardev/btcpayserver:latest-arm -f Dockerfile.linuxarm .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push rockstardev/btcpayserver:$LATEST_TAG-arm
            sudo docker push rockstardev/btcpayserver:latest-arm

  publish_docker_multiarch:
    machine:
      docker_layer_caching: true
    steps:
      - run:
          command: |
            # Restart Docker with experimental features on.
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
            #
            # Login and push Docker image to registry.
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            docker manifest create rockstardev/btcpayserver:latest 
                rockstardev/btcpayserver:latest-amd64
                rockstardev/btcpayserver:latest-arm
            docker manifest annotate rockstardev/btcpayserver:latest rockstardev/btcpayserver:latest-amd64 --os linux --arch amd64
            docker manifest annotate rockstardev/btcpayserver:latest rockstardev/btcpayserver:latest-arm --os linux --arch arm
            docker manifest push rockstardev/btcpayserver:latest      

workflows:
  version: 2
  build_and_test:
    jobs:
      - publish_docker_linuxamd64
      - publish_docker_linuxarm
      - publish_docker_multiarch:
          requires:
            - publish_docker_linuxamd64
            - publish_docker_linuxarm
